[package]
name = "plugin_ui_demo"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
eframe = { version = "0.27", default-features = false, features = ["default_fonts", "glow"] }
egui = "0.27"